### ISSUE TITLE
Replace LuckPerms API with Vault API

### ISSUE THREAD

**Issue by MrDiamond123** [CyberedCake/MBorder#5]
I had a look in the code and it appears your using the LuckPerms API, instead of the more standardized Vault API (which LuckPerms and many other permission plugins use), which would lock the server owner to only being able to use your plugin with LuckPerms (which they may not want to do)

**Comment by MrDiamond123** [comment]
[API Github](https://github.com/MilkBowl/VaultAPI/)

**Comment by CyberedCake** [comment]
Succesful
